export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
export const UPDATE_USER = 'UPDATE_USER';

export type FETCH_USER_REQUEST = typeof FETCH_USER_REQUEST;
export type FETCH_USER_SUCCESS = typeof FETCH_USER_SUCCESS;
export type FETCH_USER_FAILURE = typeof FETCH_USER_FAILURE;
export type UPDATE_USER = typeof UPDATE_USER;
